// Generated by https://pagedraw.io/pages/8436
import ClientPatrolBlock from 'pathing'
import React from 'react';
import './a4_-_3.css';

function render() {
    return <div className="a4_-_3-a4">
        <div className="a4_-_3-0">
            <div className="a4_-_3-personnel_authentica-1">
                Personnel authenticated
            </div>
        </div>
        <div className="a4_-_3-1">
            <div className="a4_-_3-we_detected_2">
                {"We detected 21 people in the building after hours this week. With the help of the Yelp Security Leadership team, we succesfully authenticated all of them."}
            </div>
        </div>
        <div className="a4_-_3-2">
            <div className="a4_-_3-2-0">
                <div className="a4_-_3-2-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1781663548485229-1521034504164-98B4446A-90F8-475F-B2FE-DEEDB396FFB6.png" className="a4_-_3-14" /> 
                </div>
            </div>
            <div className="a4_-_3-2-1">
                <div className="a4_-_3-2-1-0">
                    <div className="a4_-_3-x-9">x</div>
                </div>
            </div>
            <div className="a4_-_3-2-2">
                <div className="a4_-_3-2-2-0">
                    <div className="a4_-_3-8-8">6</div>
                </div>
            </div>
        </div>
        <div className="a4_-_3-3">
            <div className="a4_-_3-3-0">
                <div className="a4_-_3-3-0-0">
                    <div className="a4_-_3-3-0-0-0">
                        <div className="a4_-_3-path-3" /> 
                        <div className="a4_-_3-path-5" /> 
                        <div className="a4_-_3-path-1" /> 
                        <div className="a4_-_3-path-14" /> 
                        <div className="a4_-_3-path-7" /> 
                        <div className="a4_-_3-line_copy_8">
                            <div className="a4_-_3-3-0-0-0-5-0">
                                <div className="a4_-_3-path-13" /> 
                            </div>
                        </div>
                        <div className="a4_-_3-16">4</div>
                        <div className="a4_-_3-5-4">4</div>
                        <div className="a4_-_3-16-8">4</div>
                        <div className="a4_-_3-17">0</div>
                        <div className="a4_-_3-11">3</div>
                        <div className="a4_-_3-7-6">0</div>
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/5785973055203759-1521034504170-28B9FE83-A2E8-4DA3-A5E7-5893CCDBF26C.png" className="a4_-_3-149" /> 
                        <div className="a4_-_3-x-6">x</div>
                        <div className="a4_-_3-x-4">x</div>
                        <div className="a4_-_3-x-3">x</div>
                        <div className="a4_-_3-x-1">x</div>
                        <div className="a4_-_3-x-14">x</div>
                        <div className="a4_-_3-x-12">x</div>
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9922603169644023-1521034504408-00D1FCB3-C941-47D8-878A-68C8038BF89A.png" className="a4_-_3-1492" /> 
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9376735375586522-1521034504166-B9321E96-4B9A-4926-8E80-4E41EEA0B1A6.png" className="a4_-_3-14926" /> 
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8164052188796417-1521034504282-F03CD5DB-BF67-4DB3-AAD8-D2B810C51BE9.png" className="a4_-_3-149265" /> 
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7439431636629988-1521034504280-8264AF19-9E29-4681-B090-BA454900A17B.png" className="a4_-_3-1492658" /> 
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1020866281922563-1521034504168-1B04AD89-169B-4F91-81C2-9A2973CEC304.png" className="a4_-_3-14926582" /> 
                        <div className="a4_-_3-path-135" /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="a4_-_3-4">
            <div className="a4_-_3-m-1">M</div>
            <div className="a4_-_3-t-6">T</div>
            <div className="a4_-_3-w-1">W</div>
            <div className="a4_-_3-t-1">T</div>
            <div className="a4_-_3-f-2">F</div>
            <div className="a4_-_3-s_copy_2">S</div>
            <div className="a4_-_3-s-1">S</div>
        </div>
        <div className="a4_-_3-5">
            <div className="a4_-_3-our_patrols-1">Our patrols</div>
        </div>
        <div className="a4_-_3-6">
            <div className="a4_-_3-rectangle-5">
                <ClientPatrolBlock customer={this.props.customer} />
            </div>
        </div>
        <div className="a4_-_3-7">
            <div className="a4_-_3-_page_-8">3</div>
        </div>
        <div className="a4_-_3-8" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}