// Generated by https://pagedraw.io/pages/8436
import React from 'react';
import './a4_-_5.css';

function render() {
    return <div className="a4_-_5-a4">
        <div className="a4_-_5-0">
            <div className="a4_-_5-feature_roadmap-7">
                Feature roadmap
            </div>
        </div>
        <div className="a4_-_5-1">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1709776183367414-1521034504402-EFF808B4-5F12-483F-B582-769C1EA4775D.png" className="a4_-_5-bitmap-1" /> 
            <div className="a4_-_5-1-1">
                <div className="a4_-_5-1-1-0">
                    <div className="a4_-_5-1-1-0-0">
                        <div className="a4_-_5-1-1-0-0-0">
                            <div className="a4_-_5-1-1-0-0-0-0">
                                <div className="a4_-_5-_improved_connectiv-1">
                                    <br/>
                                    <div>{"	•	Improved connectivity hardware for the new robot version. "}</div>
                                    <div>{"	•	Mechanical design for the next robot version complete."}</div>
                                </div>
                                <div className="a4_-_5-recent_updates-1">
                                    Recent updates
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="a4_-_5-1-1-1">
                    <div className="a4_-_5-future_updates-1">
                        Future updates
                    </div>
                </div>
                <div className="a4_-_5-1-1-2">
                    <div className="a4_-_5-_improved_machine_l-7">
                        <div>{"	•	Improved machine learning for motion detections."}</div>
                        <div>{"	•	Alerts sent to pilots with added intelligence."}</div>
                    </div>
                </div>
            </div>
        </div>
        <div className="a4_-_5-2">
            <div className="a4_-_5-please_contact_us_if-1">
                <div>Please contact us if you have any</div>
                <div>{"questions. We’re always happy to hear from you!"}</div>
            </div>
        </div>
        <div className="a4_-_5-3">
            <div className="a4_-_5-cobalt-1">Cobalt</div>
        </div>
        <div className="a4_-_5-4">
            <div className="a4_-_5-4-4">4</div>
        </div>
        <div className="a4_-_5-5" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}