// Generated by https://pagedraw.io/pages/8436
import React from 'react';
import './a4_-_1.css';

function render() {
    return <div className="a4_-_1-a4">
        <div className="a4_-_1-0">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1632243403919618-1521034503943-EA469123-0C2F-4968-A9D8-7E6E9D096639.png" className="a4_-_1-screen_shot_2" /> 
        </div>
        <div className="a4_-_1-1">
            <div className="a4_-_1-weekly_report-2">Weekly Report</div>
        </div>
        <div className="a4_-_1-2">
            <div className="a4_-_1-february_2">
                February 26th - March 4th
            </div>
        </div>
        <div className="a4_-_1-3">
            <div className="a4_-_1-every_week_we_ve_go-1">
                {"Every week, we’ve got you covered."}
            </div>
        </div>
        <div className="a4_-_1-4">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2199153343618980-1521034504086-30B14FCB-F135-4E57-9FB9-FECF43165091.png" className="a4_-_1-tick-2" /> 
        </div>
        <div className="a4_-_1-5">
            <div className="a4_-_1-no_incidents_this_we-9">
                {"No incidents this week."}
            </div>
        </div>
        <div className="a4_-_1-6">
            <div className="a4_-_1-incidents_are_urgent-1">
                {"Incidents are urgent events in which a member of the Yelp Security Leadership team was immediately notified."}
            </div>
        </div>
        <div className="a4_-_1-7">
            <div className="a4_-_1-authenticated-4">Authenticated</div>
            <div className="a4_-_1-patrols-1">Patrols</div>
            <div className="a4_-_1-robots-1">Robots</div>
        </div>
        <div className="a4_-_1-8">
            <div className="a4_-_1-path-2">
                <div className="a4_-_1-8-0-0">
                    <div className="a4_-_1-21">21</div>
                </div>
            </div>
            <div className="a4_-_1-path-6">
                <div className="a4_-_1-8-1-0">
                    <div className="a4_-_1-108">108</div>
                </div>
            </div>
            <div className="a4_-_1-path-1">
                <div className="a4_-_1-8-2-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4294230339943354-1521034504081-C876B6CB-CCC2-4F7C-A847-1E5C3B053586.png" className="a4_-_1-bot-4" /> 
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4796367961140706-1521034504084-1BC0F0B2-B7F3-4932-8215-7D2CE4FF2BD0.png" className="a4_-_1-bot-47" /> 
                </div>
            </div>
        </div>
        <div className="a4_-_1-9">
            <div className="a4_-_1-we_authenticated_2">
                {"We authenticated 21 people in your space this week and completed 108 patrols."}
            </div>
        </div>
        <div className="a4_-_1-10">
            <div className="a4_-_1-_page_-9">1</div>
        </div>
        <div className="a4_-_1-11" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}