// Generated by https://pagedraw.io/pages/8436
import React from 'react';
import './a4_-_2.css';

function render() {
    return <div className="a4_-_2-a4">
        <div className="a4_-_2-0">
            <div className="a4_-_2-0-0">
                <div className="a4_-_2-0-0-0">
                    <div className="a4_-_2-0-0-0-0">
                        <div className="a4_-_2-path-1" /> 
                        <div className="a4_-_2-path-18" /> 
                        <div className="a4_-_2-path-15" /> 
                        <div className="a4_-_2-path-14" /> 
                        <div className="a4_-_2-path-12" /> 
                        <div className="a4_-_2-tue-1">Tue</div>
                        <div className="a4_-_2-thu-6">Thu</div>
                        <div className="a4_-_2-fri-1">Fri</div>
                        <div className="a4_-_2-wed-1">Wed</div>
                        <div className="a4_-_2-5-8">27</div>
                        <div className="a4_-_2-4-4">2</div>
                        <div className="a4_-_2-1-1">26</div>
                        <div className="a4_-_2-3-1">1</div>
                        <div className="a4_-_2-2-1">28</div>
                        <div className="a4_-_2-mon-2">Mon</div>
                        <div className="a4_-_2-12">12pm</div>
                        <div className="a4_-_2-12a">12am</div>
                        <div className="a4_-_2-6p">6pm</div>
                        <div className="a4_-_2-7">7am</div>
                        <div className="a4_-_2-6a">6am</div>
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6191921072751276-1521034504303-7A6437FC-2DA8-48C4-952D-5D2F6BECE6D4.png" className="a4_-_2-line_copy_3" /> 
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/4205028228992092-1521034504298-593D725C-6764-4584-8463-51247819BF4A.png" className="a4_-_2-line_copy-4" /> 
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1011430167811361-1521034504284-24A704F9-AAD3-4D38-9488-A69E2DB12CE6.png" className="a4_-_2-line-1" /> 
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1008550307287658-1521034504304-55704BE9-9986-41F4-9A08-4308FBF2BFC1.png" className="a4_-_2-line_copy_5" /> 
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1922004374619285-1521034504306-D6513901-379F-4E9D-905D-F96A03F2DF45.png" className="a4_-_2-line_copy_6" /> 
                    </div>
                </div>
            </div>
            <div className="a4_-_2-0-1">
                <div className="a4_-_2-0-1-0">
                    <div className="a4_-_2-0-1-0-0">
                        <div className="a4_-_2-path-7" /> 
                        <div className="a4_-_2-path-120" /> 
                        <div className="a4_-_2-sun-6">Sun</div>
                        <div className="a4_-_2-sat-1">Sat</div>
                        <div className="a4_-_2-6-1">4</div>
                        <div className="a4_-_2-5-13">3</div>
                        <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1428228869881347-1521034504287-ED226BF3-EC61-4AAD-B92C-72DC05D8FE7C.png" className="a4_-_2-line_copy_7" /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="a4_-_2-1">
            <div className="a4_-_2-what_have_we_been_up-8">
                {"What have we been up to?"}
            </div>
        </div>
        <div className="a4_-_2-2">
            <div className="a4_-_2-2-0">
                <div className="a4_-_2-2-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9070495570780506-1521034504049-2B94AAB7-BB9F-4AE3-9B6A-2C6D3DB2F316.png" className="a4_-_2-tick-9" /> 
                </div>
            </div>
            <div className="a4_-_2-authenticated_yelp_p-6">
                <div>Authenticated Yelp </div>
                <div>Personnel</div>
            </div>
            <div className="a4_-_2-2-2">
                <div className="a4_-_2-2-2-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2835414264195016-1521034504053-F1696947-0089-4933-885D-CB19A7F491E6.png" className="a4_-_2-group_copy_7" /> 
                </div>
            </div>
            <div className="a4_-_2-authenticated_facili-3">
                <div>Authenticated Facilities</div>
                <div>Personnel</div>
            </div>
        </div>
        <div className="a4_-_2-3">
            <div className="a4_-_2-3-0">
                <div className="a4_-_2-3-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1331823589467994-1521034504044-F1EC80A8-AF6E-4A91-84EA-66A65360D7C7.png" className="a4_-_2-tick-1" /> 
                </div>
            </div>
            <div className="a4_-_2-completed_patrols-1">
                Completed patrols
            </div>
            <div className="a4_-_2-3-2">
                <div className="a4_-_2-3-2-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1697582179031142-1521034504047-E0997D73-3737-45E5-B4D3-AE77598B7885.png" className="a4_-_2-tick-16" /> 
                </div>
            </div>
            <div className="a4_-_2-reported_incidents-1">
                Reported Incidents
            </div>
        </div>
        <div className="a4_-_2-4">
            <div className="a4_-_2-_-1">
                <div>{"We covered a lot of ground, 5.60 miles to be exact."}</div>
                <div>{"At that rate, it would take us 1200 weeks to circle the moon!"}</div>
            </div>
        </div>
        <div className="a4_-_2-5">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9033993476676920-1521034504079-3098AD18-B512-449C-9314-10D2F5B69AC6.png" className="a4_-_2-bitmap-9" /> 
            <div className="a4_-_2-5-1">
                <div className="a4_-_2-5-1-0">
                    <div className="a4_-_2-_page_-1">2</div>
                </div>
            </div>
        </div>
        <div className="a4_-_2-6" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}