// Generated by https://pagedraw.io/pages/4958
import PersonnelAuthenticated from '../../src/components/PersonnelAuthenticated'
import Patrols from '../../src/components/Patrols'
import {reportData} from '../../src/App.js'
import React from 'react';

function render() {
    return React.createElement('div', {"className": "activity-summary-activity-summary-1"},
        React.createElement('style', {},
            "@font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            \n\
            .activity-summary-activity-summary-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                flex-grow: 1;\n\
                padding-top: 58px;\n\
                background: #FFFFFF;\n\
            }\n\
            \n\
            .activity-summary-0 {\n\
                display: flex;\n\
                padding-left: 179px;\n\
                padding-right: 173px;\n\
            }\n\
            \n\
            .activity-summary-personnel_authentica-1 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 22px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.640625px;\n\
            }\n\
            \n\
            .activity-summary-1 {\n\
                display: flex;\n\
                margin-top: 16px;\n\
                padding-left: 126px;\n\
                padding-right: 128px;\n\
            }\n\
            \n\
            .activity-summary-rectangle_8 {\n\
                width: 341px;\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .activity-summary-2 {\n\
                display: flex;\n\
                margin-top: 21px;\n\
                padding-left: 155px;\n\
                padding-right: 419px;\n\
            }\n\
            \n\
            .activity-summary-14 {\n\
                width: 7px;\n\
                height: 15px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .activity-summary-x1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 2px;\n\
                padding-top: 2px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 11px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.5625px;\n\
            }\n\
            \n\
            .activity-summary-3 {\n\
                display: flex;\n\
                margin-top: 2px;\n\
                padding-left: 152px;\n\
                padding-right: 152px;\n\
            }\n\
            \n\
            .activity-summary-path-2 {\n\
                width: 34px;\n\
                height: 120px;\n\
                flex-shrink: 0;\n\
                background: #BFF4E8;\n\
            }\n\
            \n\
            .activity-summary-3-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 8px;\n\
                padding-top: 48px;\n\
            }\n\
            \n\
            .activity-summary-3-1-0 {\n\
                display: flex;\n\
                padding-left: 4px;\n\
                padding-right: 8px;\n\
            }\n\
            \n\
            .activity-summary-149 {\n\
                width: 7px;\n\
                height: 16px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .activity-summary-x5 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 3px;\n\
                padding-top: 1px;\n\
                padding-bottom: 2px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 11px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.375px;\n\
            }\n\
            \n\
            .activity-summary-3-1-1 {\n\
                display: flex;\n\
                margin-top: 1px;\n\
            }\n\
            \n\
            .activity-summary-path-5 {\n\
                width: 34px;\n\
                height: 55px;\n\
                flex-shrink: 0;\n\
                background: #BFF4E8;\n\
            }\n\
            \n\
            .activity-summary-3-2 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 10px;\n\
                padding-top: 48px;\n\
            }\n\
            \n\
            .activity-summary-3-2-0 {\n\
                display: flex;\n\
                padding-left: 2px;\n\
                padding-right: 9px;\n\
            }\n\
            \n\
            .activity-summary-1492 {\n\
                width: 7px;\n\
                height: 15px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .activity-summary-x5-9 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 4px;\n\
                padding-top: 1px;\n\
                padding-bottom: 1px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 11px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.375px;\n\
            }\n\
            \n\
            .activity-summary-3-2-1 {\n\
                display: flex;\n\
                margin-top: 2px;\n\
            }\n\
            \n\
            .activity-summary-path-23 {\n\
                width: 34px;\n\
                height: 55px;\n\
                flex-shrink: 0;\n\
                background: #BFF4E8;\n\
            }\n\
            \n\
            .activity-summary-3-3 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 9px;\n\
                padding-top: 27px;\n\
            }\n\
            \n\
            .activity-summary-3-3-0 {\n\
                display: flex;\n\
                padding-left: 4px;\n\
                padding-right: 6px;\n\
            }\n\
            \n\
            .activity-summary-14926 {\n\
                width: 7px;\n\
                height: 15px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .activity-summary-x7 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 5px;\n\
                padding-top: 1px;\n\
                padding-bottom: 1px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 11px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.375px;\n\
            }\n\
            \n\
            .activity-summary-3-3-1 {\n\
                display: flex;\n\
                margin-top: 2px;\n\
            }\n\
            \n\
            .activity-summary-path-59 {\n\
                width: 34px;\n\
                height: 76px;\n\
                flex-shrink: 0;\n\
                background: #BFF4E8;\n\
            }\n\
            \n\
            .activity-summary-3-4 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 8px;\n\
                padding-top: 48px;\n\
            }\n\
            \n\
            .activity-summary-3-4-0 {\n\
                display: flex;\n\
                padding-left: 4px;\n\
                padding-right: 9px;\n\
            }\n\
            \n\
            .activity-summary-149265 {\n\
                width: 7px;\n\
                height: 16px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .activity-summary-x5-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 3px;\n\
                padding-top: 1px;\n\
                padding-bottom: 2px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 11px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.375px;\n\
            }\n\
            \n\
            .activity-summary-3-4-1 {\n\
                display: flex;\n\
                margin-top: 1px;\n\
            }\n\
            \n\
            .activity-summary-path-1 {\n\
                width: 35px;\n\
                height: 55px;\n\
                flex-shrink: 0;\n\
                background: #BFF4E8;\n\
            }\n\
            \n\
            .activity-summary-3-5 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 8px;\n\
                padding-top: 48px;\n\
            }\n\
            \n\
            .activity-summary-3-5-0 {\n\
                display: flex;\n\
                padding-left: 4px;\n\
                padding-right: 6px;\n\
            }\n\
            \n\
            .activity-summary-1492658 {\n\
                width: 7px;\n\
                height: 15px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .activity-summary-x5-95 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 5px;\n\
                padding-top: 1px;\n\
                padding-bottom: 1px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 11px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.375px;\n\
            }\n\
            \n\
            .activity-summary-3-5-1 {\n\
                display: flex;\n\
                margin-top: 2px;\n\
            }\n\
            \n\
            .activity-summary-path-14 {\n\
                width: 34px;\n\
                height: 55px;\n\
                flex-shrink: 0;\n\
                background: #BFF4E8;\n\
            }\n\
            \n\
            .activity-summary-3-6 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 9px;\n\
                padding-top: 38px;\n\
            }\n\
            \n\
            .activity-summary-3-6-0 {\n\
                display: flex;\n\
                padding-left: 6px;\n\
                padding-right: 5px;\n\
            }\n\
            \n\
            .activity-summary-14926582 {\n\
                width: 7px;\n\
                height: 15px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .activity-summary-x6 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 4px;\n\
                padding-top: 1px;\n\
                padding-bottom: 1px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 11px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.375px;\n\
            }\n\
            \n\
            .activity-summary-3-6-1 {\n\
                display: flex;\n\
                margin-top: 2px;\n\
            }\n\
            \n\
            .activity-summary-path-15 {\n\
                width: 34px;\n\
                height: 65px;\n\
                flex-shrink: 0;\n\
                background: #BFF4E8;\n\
            }\n\
            \n\
            .activity-summary-4 {\n\
                display: flex;\n\
                padding-left: 153px;\n\
                padding-right: 152px;\n\
            }\n\
            \n\
            .activity-summary-rectangle-1 {\n\
                width: 290px;\n\
                height: 2px;\n\
                flex-shrink: 0;\n\
                background: rgb(191, 244, 232);\n\
            }\n\
            \n\
            .activity-summary-5 {\n\
                display: flex;\n\
                margin-top: 2px;\n\
                padding-left: 162px;\n\
                padding-right: 164px;\n\
            }\n\
            \n\
            .activity-summary-m-1 {\n\
                width: 14px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-t-6 {\n\
                width: 10px;\n\
                flex-shrink: 0;\n\
                margin-left: 31px;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-w-1 {\n\
                width: 16px;\n\
                flex-shrink: 0;\n\
                margin-left: 30px;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-t-1 {\n\
                width: 9px;\n\
                flex-shrink: 0;\n\
                margin-left: 30px;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-f-2 {\n\
                width: 9px;\n\
                flex-shrink: 0;\n\
                margin-left: 34px;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-s_copy_2 {\n\
                width: 9px;\n\
                flex-shrink: 0;\n\
                margin-left: 34px;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-s-1 {\n\
                width: 9px;\n\
                flex-shrink: 0;\n\
                margin-left: 34px;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-6 {\n\
                display: flex;\n\
                margin-top: 63px;\n\
                padding-left: 200px;\n\
                padding-right: 199px;\n\
            }\n\
            \n\
            .activity-summary-our_patrols-1 {\n\
                width: 196px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 22px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-7 {\n\
                display: flex;\n\
                margin-top: 19px;\n\
                padding-left: 73px;\n\
                padding-right: 70px;\n\
            }\n\
            \n\
            .activity-summary-patrols_override-1 {\n\
                width: 452px;\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .activity-summary-8 {\n\
                display: flex;\n\
                margin-top: 46px;\n\
                padding-left: 539px;\n\
                padding-right: 12px;\n\
            }\n\
            \n\
            .activity-summary-_page_-8 {\n\
                width: 44px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 14px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .activity-summary-9 {\n\
                flex-grow: 1;\n\
                flex-basis: 0px;\n\
            }\n\
            \n\
            * {\n\
                box-sizing: border-box;\n\
            }\n\
            \n\
            body {\n\
                margin: 0;\n\
            }\n\
            \n\
            button:hover {\n\
                cursor: pointer;\n\
            }\n\
            \n\
            a {\n\
                text-decoration: none;\n\
                color: inherit;\n\
            }\n\
            \n\
            .pd-onhover-parent >.pd-onhover {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > .pd-onhover {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent > .pd-onactive {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > .pd-onactive {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {\n\
                display: none;\n\
            }"
        ),
        React.createElement('div', {"className": "activity-summary-0"},
            React.createElement('div', {"className": "activity-summary-personnel_authentica-1"},
                "Personnel authenticated"
            )
        ),
        React.createElement('div', {"className": "activity-summary-1"},
            React.createElement('div', {"className": "activity-summary-rectangle_8"},
                <PersonnelAuthenticated numberAuthenticatedDaily={reportData.numberAuthenticatedDaily} clientTeamName={reportData.customerTeamName}/>
            )
        ),
        React.createElement('div', {"className": "activity-summary-2"},
            React.createElement('img', {"src": "https://pagedraw-images.s3.amazonaws.com/1007147827729374.png", "className": "activity-summary-14"}),
            React.createElement('div', {"className": "activity-summary-x1"},
                "  11"
            )
        ),
        React.createElement('div', {"className": "activity-summary-3"},
            React.createElement('div', {"className": "activity-summary-path-2"}),
            React.createElement('div', {"className": "activity-summary-3-1"},
                React.createElement('div', {"className": "activity-summary-3-1-0"},
                    React.createElement('img', {"src": "https://pagedraw-images.s3.amazonaws.com/8833869689528583.png", "className": "activity-summary-149"}),
                    React.createElement('div', {"className": "activity-summary-x5"},
                        "x5"
                    )
                ),
                React.createElement('div', {"className": "activity-summary-3-1-1"},
                    React.createElement('div', {"className": "activity-summary-path-5"})
                )
            ),
            React.createElement('div', {"className": "activity-summary-3-2"},
                React.createElement('div', {"className": "activity-summary-3-2-0"},
                    React.createElement('img', {"src": "https://pagedraw-images.s3.amazonaws.com/1147139819537635.png", "className": "activity-summary-1492"}),
                    React.createElement('div', {"className": "activity-summary-x5-9"},
                        "x5"
                    )
                ),
                React.createElement('div', {"className": "activity-summary-3-2-1"},
                    React.createElement('div', {"className": "activity-summary-path-23"})
                )
            ),
            React.createElement('div', {"className": "activity-summary-3-3"},
                React.createElement('div', {"className": "activity-summary-3-3-0"},
                    React.createElement('img', {"src": "https://pagedraw-images.s3.amazonaws.com/1556080224496606.png", "className": "activity-summary-14926"}),
                    React.createElement('div', {"className": "activity-summary-x7"},
                        "x7"
                    )
                ),
                React.createElement('div', {"className": "activity-summary-3-3-1"},
                    React.createElement('div', {"className": "activity-summary-path-59"})
                )
            ),
            React.createElement('div', {"className": "activity-summary-3-4"},
                React.createElement('div', {"className": "activity-summary-3-4-0"},
                    React.createElement('img', {"src": "https://pagedraw-images.s3.amazonaws.com/8308198470800867.png", "className": "activity-summary-149265"}),
                    React.createElement('div', {"className": "activity-summary-x5-1"},
                        "x5"
                    )
                ),
                React.createElement('div', {"className": "activity-summary-3-4-1"},
                    React.createElement('div', {"className": "activity-summary-path-1"})
                )
            ),
            React.createElement('div', {"className": "activity-summary-3-5"},
                React.createElement('div', {"className": "activity-summary-3-5-0"},
                    React.createElement('img', {"src": "https://pagedraw-images.s3.amazonaws.com/1844296245062956.png", "className": "activity-summary-1492658"}),
                    React.createElement('div', {"className": "activity-summary-x5-95"},
                        "x5"
                    )
                ),
                React.createElement('div', {"className": "activity-summary-3-5-1"},
                    React.createElement('div', {"className": "activity-summary-path-14"})
                )
            ),
            React.createElement('div', {"className": "activity-summary-3-6"},
                React.createElement('div', {"className": "activity-summary-3-6-0"},
                    React.createElement('img', {"src": "https://pagedraw-images.s3.amazonaws.com/1622246397088166.png", "className": "activity-summary-14926582"}),
                    React.createElement('div', {"className": "activity-summary-x6"},
                        "x6"
                    )
                ),
                React.createElement('div', {"className": "activity-summary-3-6-1"},
                    React.createElement('div', {"className": "activity-summary-path-15"})
                )
            )
        ),
        React.createElement('div', {"className": "activity-summary-4"},
            React.createElement('div', {"className": "activity-summary-rectangle-1"})
        ),
        React.createElement('div', {"className": "activity-summary-5"},
            React.createElement('div', {"className": "activity-summary-m-1"},
                "M"
            ),
            React.createElement('div', {"className": "activity-summary-t-6"},
                "T"
            ),
            React.createElement('div', {"className": "activity-summary-w-1"},
                "W"
            ),
            React.createElement('div', {"className": "activity-summary-t-1"},
                "T"
            ),
            React.createElement('div', {"className": "activity-summary-f-2"},
                "F"
            ),
            React.createElement('div', {"className": "activity-summary-s_copy_2"},
                "S"
            ),
            React.createElement('div', {"className": "activity-summary-s-1"},
                "S"
            )
        ),
        React.createElement('div', {"className": "activity-summary-6"},
            React.createElement('div', {"className": "activity-summary-our_patrols-1"},
                "Our patrols"
            )
        ),
        React.createElement('div', {"className": "activity-summary-7"},
            React.createElement('div', {"className": "activity-summary-patrols_override-1"},
                <Patrols/>
            )
        ),
        React.createElement('div', {"className": "activity-summary-8"},
            React.createElement('div', {"className": "activity-summary-_page_-8"},
                "3"
            )
        ),
        React.createElement('div', {"className": "activity-summary-9"})
    );
};

export default function(props) {
    return render.apply({props: props});
}