// Generated by https://pagedraw.io/pages/6544
import React from 'react';
import './component_1.css';

function render() {
    return <div className="component_1-component_1">
        <div className="component_1-0">
            <img src="https://ucarecdn.com/24ecbcb7-2825-4769-9585-3222d4a45445/" className="component_1-image-2" /> 
            <div className="component_1-0-1">
                <div className="component_1-0-1-0">
                    <div className="component_1-text_2">
                        <div>{"Your Cobalt Control System. "}</div>
                        <div>{"So easy to use."}</div>
                    </div>
                </div>
            </div>
        </div>
        <div className="component_1-1">
            <input type="text" placeholder="Username" className="component_1-text_input-4" /> 
        </div>
        <div className="component_1-2">
            <input type="text" placeholder="Password" className="component_1-text_input-7" /> 
        </div>
        <div className="component_1-3">
            <div className="component_1-rectangle-8">
                <div className="component_1-3-0-0">
                    <div className="component_1-text-9">Login</div>
                </div>
            </div>
        </div>
        <div className="component_1-4">
            <img src="https://ucarecdn.com/24ecbcb7-2825-4769-9585-3222d4a45445/" className="component_1-image-5" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}