// Generated by https://pagedraw.io/pages/4958
import GreenTick from '../../src/components/GreenTick'
import IncidentsText from '../../src/components/IncidentsText'
import Logo from '../../src/components/Logo'
import PageOneFooterText from '../../src/components/PageOneFooterText'
import {reportData} from '../../src/App.js'
import React from 'react';

function render() {
    return React.createElement('div', {"className": "cover-cover-1"},
        React.createElement('style', {},
            "@font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            \n\
            .cover-cover-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                flex-grow: 1;\n\
                padding-top: 48px;\n\
                background: #FFFFFF;\n\
            }\n\
            \n\
            .cover-0 {\n\
                display: flex;\n\
                padding-left: 238px;\n\
                padding-right: 231px;\n\
            }\n\
            \n\
            .cover-rectangle_4 {\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .cover-1 {\n\
                display: flex;\n\
                margin-top: 18px;\n\
                padding-left: 233px;\n\
                padding-right: 235px;\n\
            }\n\
            \n\
            .cover-weekly_report-2 {\n\
                width: 127px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 14px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .cover-2 {\n\
                display: flex;\n\
                margin-top: 10px;\n\
                padding-left: 187px;\n\
                padding-right: 186px;\n\
            }\n\
            \n\
            .cover-october_2 {\n\
                width: 222px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .cover-3 {\n\
                display: flex;\n\
                margin-top: 92px;\n\
                padding-left: 89px;\n\
                padding-right: 78px;\n\
            }\n\
            \n\
            .cover-every_week_we_ve_go-1 {\n\
                width: 428px;\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 24px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: 200;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .cover-4 {\n\
                display: flex;\n\
                margin-top: 32px;\n\
                padding-left: 252px;\n\
                padding-right: 238px;\n\
            }\n\
            \n\
            .cover-rectangle_3 {\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .cover-5 {\n\
                display: flex;\n\
                margin-top: 21px;\n\
                padding-left: 203px;\n\
                padding-right: 191px;\n\
            }\n\
            \n\
            .cover-text_3 {\n\
                width: 201px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: #000000;\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .cover-6 {\n\
                display: flex;\n\
                margin-top: 17px;\n\
                padding-left: 112px;\n\
                padding-right: 101px;\n\
            }\n\
            \n\
            .cover-rectangle_5 {\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .cover-7 {\n\
                display: flex;\n\
                margin-top: 60px;\n\
                padding-left: 67px;\n\
                padding-right: 101px;\n\
            }\n\
            \n\
            .cover-authenticated-4 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.875px;\n\
            }\n\
            \n\
            .cover-patrols-1 {\n\
                flex-shrink: 0;\n\
                margin-left: 89px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.8125px;\n\
            }\n\
            \n\
            .cover-robots-1 {\n\
                flex-shrink: 0;\n\
                margin-left: 108px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.265625px;\n\
            }\n\
            \n\
            .cover-8 {\n\
                display: flex;\n\
                margin-top: 14px;\n\
                padding-left: 72px;\n\
                padding-right: 72px;\n\
            }\n\
            \n\
            .cover-path-2 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                padding-top: 23px;\n\
                padding-bottom: 24px;\n\
                background: rgb(255, 255, 255);\n\
                border: 2px solid #0083C5;\n\
            }\n\
            \n\
            .cover-8-0-0 {\n\
                display: flex;\n\
                padding-left: 42px;\n\
                padding-right: 42px;\n\
            }\n\
            \n\
            .cover-42 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 20px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.796875px;\n\
            }\n\
            \n\
            .cover-path-6 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 61px;\n\
                padding-top: 23px;\n\
                padding-bottom: 24px;\n\
                background: rgb(255, 255, 255);\n\
                border: 2px solid #0083C5;\n\
            }\n\
            \n\
            .cover-8-1-0 {\n\
                display: flex;\n\
                padding-left: 36px;\n\
                padding-right: 37px;\n\
            }\n\
            \n\
            .cover-15 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 20px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.1875px;\n\
            }\n\
            \n\
            .cover-path-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 54px;\n\
                padding-top: 23px;\n\
                padding-bottom: 23px;\n\
                background: rgb(255, 255, 255);\n\
                border: 2px solid #0083C5;\n\
            }\n\
            \n\
            .cover-8-2-0 {\n\
                display: flex;\n\
                padding-left: 43px;\n\
                padding-right: 43px;\n\
            }\n\
            \n\
            .cover-image-7 {\n\
                width: 10px;\n\
                height: 25px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .cover-image-4 {\n\
                width: 10px;\n\
                height: 25px;\n\
                flex-shrink: 0;\n\
                margin-left: 2px;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .cover-9 {\n\
                display: flex;\n\
                margin-top: 57px;\n\
                padding-left: 105px;\n\
            }\n\
            \n\
            .cover-rectangle_2 {\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .cover-9-1 {\n\
                height: 0px;\n\
                flex-grow: 1;\n\
                flex-basis: 0px;\n\
            }\n\
            \n\
            .cover-10 {\n\
                display: flex;\n\
                margin-top: 51px;\n\
                padding-left: 539px;\n\
                padding-right: 47px;\n\
            }\n\
            \n\
            .cover-_page_-9 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 14px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.875px;\n\
            }\n\
            \n\
            .cover-11 {\n\
                width: 0px;\n\
                flex-grow: 1;\n\
                flex-basis: 0px;\n\
            }\n\
            \n\
            * {\n\
                box-sizing: border-box;\n\
            }\n\
            \n\
            body {\n\
                margin: 0;\n\
            }\n\
            \n\
            button:hover {\n\
                cursor: pointer;\n\
            }\n\
            \n\
            a {\n\
                text-decoration: none;\n\
                color: inherit;\n\
            }\n\
            \n\
            .pd-onhover-parent >.pd-onhover {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > .pd-onhover {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent > .pd-onactive {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > .pd-onactive {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {\n\
                display: none;\n\
            }"
        ),
        React.createElement('div', {"className": "cover-0"},
            React.createElement('div', {"className": "cover-rectangle_4"},
                <Logo/>
            )
        ),
        React.createElement('div', {"className": "cover-1"},
            React.createElement('div', {"className": "cover-weekly_report-2"},
                "Weekly Report"
            )
        ),
        React.createElement('div', {"className": "cover-2"},
            React.createElement('div', {"className": "cover-october_2"},
                this.props.timePeriod
            )
        ),
        React.createElement('div', {"className": "cover-3"},
            React.createElement('div', {"className": "cover-every_week_we_ve_go-1"},
                "Every week, we’ve got you covered."
            )
        ),
        React.createElement('div', {"className": "cover-4"},
            React.createElement('div', {"className": "cover-rectangle_3"},
                <GreenTick big={true}/>
            )
        ),
        React.createElement('div', {"className": "cover-5"},
            React.createElement('div', {"className": "cover-text_3"},
                "No incidents this week."
            )
        ),
        React.createElement('div', {"className": "cover-6"},
            React.createElement('div', {"className": "cover-rectangle_5"},
                <IncidentsText clientTeamName={reportData.customerTeamName}/>
            )
        ),
        React.createElement('div', {"className": "cover-7"},
            React.createElement('div', {"className": "cover-authenticated-4"},
                "Authenticated"
            ),
            React.createElement('div', {"className": "cover-patrols-1"},
                "Patrols"
            ),
            React.createElement('div', {"className": "cover-robots-1"},
                "Robots"
            )
        ),
        React.createElement('div', {"className": "cover-8"},
            React.createElement('div', {"className": "cover-path-2"},
                React.createElement('div', {"className": "cover-8-0-0"},
                    React.createElement('div', {"className": "cover-42"},
                        this.props.numberOfAuthenticated
                    )
                )
            ),
            React.createElement('div', {"className": "cover-path-6"},
                React.createElement('div', {"className": "cover-8-1-0"},
                    React.createElement('div', {"className": "cover-15"},
                        this.props.numberOfPatrols
                    )
                )
            ),
            React.createElement('div', {"className": "cover-path-1"},
                React.createElement('div', {"className": "cover-8-2-0"},
                    React.createElement('img', {"src": "https://ucarecdn.com/8f9ed4b4-6867-484c-8521-149ab2b77b82/", "className": "cover-image-7"}),
                    React.createElement('img', {"src": "https://ucarecdn.com/8f9ed4b4-6867-484c-8521-149ab2b77b82/", "className": "cover-image-4"})
                )
            )
        ),
        React.createElement('div', {"className": "cover-9"},
            React.createElement('div', {"className": "cover-rectangle_2"},
                <PageOneFooterText numberOfAuthenticated={reportData.numberOfAuthenticated} numberOfPatrols={reportData.numberOfPatrols}/>
            ),
            React.createElement('div', {"className": "cover-9-1"})
        ),
        React.createElement('div', {"className": "cover-10"},
            React.createElement('div', {"className": "cover-_page_-9"},
                "1"
            )
        ),
        React.createElement('div', {"className": "cover-11"})
    );
};

export default function(props) {
    return render.apply({props: props});
}