// Generated by https://pagedraw.io/pages/4958
import React from 'react';

function render() {
    return React.createElement('div', {"className": "feature-roadmap-feature-roadmap-8"},
        React.createElement('style', {},
            "@font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            \n\
            .feature-roadmap-feature-roadmap-8 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                flex-grow: 1;\n\
                padding-top: 82px;\n\
                background: #FFFFFF;\n\
            }\n\
            \n\
            .feature-roadmap-0 {\n\
                display: flex;\n\
                padding-left: 209px;\n\
                padding-right: 213px;\n\
            }\n\
            \n\
            .feature-roadmap-feature_roadmap-7 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(0, 0, 0, 1);\n\
                font-size: 22px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.46875px;\n\
            }\n\
            \n\
            .feature-roadmap-1 {\n\
                display: flex;\n\
                margin-top: 69px;\n\
                padding-left: 40px;\n\
                padding-right: 71px;\n\
            }\n\
            \n\
            .feature-roadmap-bitmap-1 {\n\
                width: 169px;\n\
                height: 313px;\n\
                flex-shrink: 0;\n\
                border-width: 0px;\n\
            }\n\
            \n\
            .feature-roadmap-1-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 12px;\n\
                padding-bottom: 159px;\n\
            }\n\
            \n\
            .feature-roadmap-1-1-0 {\n\
                display: flex;\n\
                padding-right: 185px;\n\
            }\n\
            \n\
            .feature-roadmap-recent_updates-1 {\n\
                width: 118px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .feature-roadmap-1-1-1 {\n\
                display: flex;\n\
                margin-top: 5px;\n\
            }\n\
            \n\
            .feature-roadmap-_better_wifi_connec-1 {\n\
                width: 303px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: 23px;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .feature-roadmap-1-1-2 {\n\
                display: flex;\n\
                margin-top: 37px;\n\
                padding-right: 193px;\n\
            }\n\
            \n\
            .feature-roadmap-future_updates-4 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.03125px;\n\
            }\n\
            \n\
            .feature-roadmap-1-1-3 {\n\
                display: flex;\n\
                margin-top: 5px;\n\
                padding-right: 18px;\n\
            }\n\
            \n\
            .feature-roadmap-_increase_robot_rel-1 {\n\
                width: 285px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: 23px;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .feature-roadmap-2 {\n\
                display: flex;\n\
                margin-top: 40px;\n\
                padding-left: 91px;\n\
                padding-right: 106px;\n\
            }\n\
            \n\
            .feature-roadmap-please_contact_us_if-1 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.703125px;\n\
            }\n\
            \n\
            .feature-roadmap-3 {\n\
                display: flex;\n\
                margin-top: 24px;\n\
                padding-left: 266px;\n\
                padding-right: 273px;\n\
            }\n\
            \n\
            .feature-roadmap-cobalt-1 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: italic;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.9375px;\n\
            }\n\
            \n\
            .feature-roadmap-4 {\n\
                display: flex;\n\
                margin-top: 161px;\n\
                padding-left: 539px;\n\
                padding-right: 48px;\n\
            }\n\
            \n\
            .feature-roadmap-4-4 {\n\
                flex-shrink: 0;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 14px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.203125px;\n\
            }\n\
            \n\
            .feature-roadmap-5 {\n\
                flex-grow: 1;\n\
                flex-basis: 0px;\n\
            }\n\
            \n\
            * {\n\
                box-sizing: border-box;\n\
            }\n\
            \n\
            body {\n\
                margin: 0;\n\
            }\n\
            \n\
            button:hover {\n\
                cursor: pointer;\n\
            }\n\
            \n\
            a {\n\
                text-decoration: none;\n\
                color: inherit;\n\
            }\n\
            \n\
            .pd-onhover-parent >.pd-onhover {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > .pd-onhover {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent > .pd-onactive {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > .pd-onactive {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {\n\
                display: none;\n\
            }"
        ),
        React.createElement('div', {"className": "feature-roadmap-0"},
            React.createElement('div', {"className": "feature-roadmap-feature_roadmap-7"},
                "Feature roadmap"
            )
        ),
        React.createElement('div', {"className": "feature-roadmap-1"},
            React.createElement('img', {"src": "https://pagedraw-images.s3.amazonaws.com/1709776183367414.png", "className": "feature-roadmap-bitmap-1"}),
            React.createElement('div', {"className": "feature-roadmap-1-1"},
                React.createElement('div', {"className": "feature-roadmap-1-1-0"},
                    React.createElement('div', {"className": "feature-roadmap-recent_updates-1"},
                        "Recent updates"
                    )
                ),
                React.createElement('div', {"className": "feature-roadmap-1-1-1"},
                    React.createElement('div', {"className": "feature-roadmap-_better_wifi_connec-1"},
                        "\t•\tBetter wifi connection resiliency"
                    )
                ),
                React.createElement('div', {"className": "feature-roadmap-1-1-2"},
                    React.createElement('div', {"className": "feature-roadmap-future_updates-4"},
                        "Future updates"
                    )
                ),
                React.createElement('div', {"className": "feature-roadmap-1-1-3"},
                    React.createElement('div', {"className": "feature-roadmap-_increase_robot_rel-1"},
                        "\t•\tIncrease robot reliability\n\t•\tMore secure storage on the robot"
                    )
                )
            )
        ),
        React.createElement('div', {"className": "feature-roadmap-2"},
            React.createElement('div', {"className": "feature-roadmap-please_contact_us_if-1"},
                "Please contact us if you have any\nquestions. We’re always happy to hear from you!"
            )
        ),
        React.createElement('div', {"className": "feature-roadmap-3"},
            React.createElement('div', {"className": "feature-roadmap-cobalt-1"},
                "Cobalt"
            )
        ),
        React.createElement('div', {"className": "feature-roadmap-4"},
            React.createElement('div', {"className": "feature-roadmap-4-4"},
                "4"
            )
        ),
        React.createElement('div', {"className": "feature-roadmap-5"})
    );
};

export default function(props) {
    return render.apply({props: props});
}