// Generated by https://pagedraw.io/pages/6556
import React from 'react';
import './navigation.css';

function render() {
    return React.createElement('div', {"className": "navigation-navigation-6"},
        React.createElement('div', {"className": "navigation-0"},
            React.createElement('div', {"className": "navigation-text-5"},
                this.props.userText
            )
        ),
        React.createElement('div', {"className": "navigation-1"},
            React.createElement('div', {"onClick": this.props.logout, "className": "navigation-text-7"},
                "Logout"
            )
        ),
        React.createElement('div', {"className": "navigation-2"},
            React.createElement('div', {"className": "navigation-text_2"},
                this.props.pageName
            )
        ),
        React.createElement('div', {"className": "navigation-3"},
            React.createElement('div', {"onClick": this.props.navigate, "className": "navigation-rectangle_2"},
                React.createElement('div', {"className": "navigation-3-0-0"},
                    React.createElement('div', {"className": "navigation-text_3"},
                        this.props.linkText
                    )
                )
            )
        )
    );
};

export default function(props) {
    return render.apply({props: props});
}