// Generated by https://pagedraw.io/pages/4958
import GreenTick from '../../src/components/GreenTick'
import OperationalHoursGraph from '../../src/components/OperationalHoursGraph'
import DistanceCovered from '../../src/components/DistanceCovered'
import OperationalText from '../../src/components/OperationalText'
import {reportData} from '../../src/App.js'
import React from 'react';

function render() {
    return React.createElement('div', {"className": "operational-hours-operational-hours-1"},
        React.createElement('style', {},
            "@font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            @font-face {\n\
                font-family: \"AvenirNext-Regular\";\n\
                font-style: normal;\n\
                font-weight: 400;\n\
                src: url(https://pagedraw-fonts.s3.us-west-2.amazonaws.com/AvenirNext-Regular99722bbf-93bb-46ec-85ba-8c392046981d) format(\"opentype\");\n\
            }\n\
            \n\
            .operational-hours-operational-hours-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                flex-grow: 1;\n\
                padding-top: 50px;\n\
                background: #FFFFFF;\n\
            }\n\
            \n\
            .operational-hours-0 {\n\
                display: flex;\n\
                padding-left: 88px;\n\
                padding-right: 88px;\n\
            }\n\
            \n\
            .operational-hours-0-0 {\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .operational-hours-0-0-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .operational-hours-0-0-0-0 {\n\
                width: 419px;\n\
                height: 351px;\n\
                flex-shrink: 0;\n\
                position: relative;\n\
            }\n\
            \n\
            .operational-hours-rectangle_1 {\n\
                width: 377px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 82px;\n\
                left: 41px;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .operational-hours-4-5 {\n\
                width: 41px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 22px;\n\
                left: 263px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(0, 0, 0, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-6-1 {\n\
                width: 41px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 22px;\n\
                left: 372px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(0, 0, 0, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-5-1 {\n\
                width: 41px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 22px;\n\
                left: 318px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(0, 0, 0, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-sun-6 {\n\
                width: 47px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 44px;\n\
                left: 372px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-2-11 {\n\
                width: 36px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 22px;\n\
                left: 47px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(0, 0, 0, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-mon-2 {\n\
                width: 41px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 44px;\n\
                left: 47px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-fri-1 {\n\
                width: 41px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 44px;\n\
                left: 263px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-sat-1 {\n\
                width: 41px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 44px;\n\
                left: 318px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-tue-1 {\n\
                width: 41px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 44px;\n\
                left: 102px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-wed-1 {\n\
                width: 41px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 44px;\n\
                left: 156px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-thu-6 {\n\
                width: 38px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 44px;\n\
                left: 210px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-2-5 {\n\
                width: 31px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 22px;\n\
                left: 160px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(0, 0, 0, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-12 {\n\
                width: 45px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 150px;\n\
                left: 0px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 12px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-3-37 {\n\
                width: 28px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 22px;\n\
                left: 210px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(0, 0, 0, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-1-8 {\n\
                width: 26px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 22px;\n\
                left: 109px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(0, 0, 0, 1);\n\
                font-size: 18px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: center;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-12a {\n\
                width: 36px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 275px;\n\
                left: 0px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 12px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-6p {\n\
                width: 36px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 212px;\n\
                left: 0px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 12px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-7 {\n\
                width: 33px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 78px;\n\
                left: 0px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 12px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-6a {\n\
                width: 33px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 337px;\n\
                left: 0px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 12px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-line_copy_3 {\n\
                width: 1px;\n\
                height: 351px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 0px;\n\
                left: 202px;\n\
                background: #D8D8D8;\n\
            }\n\
            \n\
            .operational-hours-line_copy-4 {\n\
                width: 1px;\n\
                height: 351px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 0px;\n\
                left: 256px;\n\
                background: #D8D8D8;\n\
            }\n\
            \n\
            .operational-hours-line_copy_6 {\n\
                width: 1px;\n\
                height: 351px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 0px;\n\
                left: 148px;\n\
                background: #D8D8D8;\n\
            }\n\
            \n\
            .operational-hours-line_copy_7 {\n\
                width: 1px;\n\
                height: 351px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 0px;\n\
                left: 365px;\n\
                background: #D8D8D8;\n\
            }\n\
            \n\
            .operational-hours-line-1 {\n\
                width: 1px;\n\
                height: 351px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 0px;\n\
                left: 94px;\n\
                background: #D8D8D8;\n\
            }\n\
            \n\
            .operational-hours-line_copy_5 {\n\
                width: 1px;\n\
                height: 351px;\n\
                flex-grow: 1;\n\
                position: absolute;\n\
                top: 0px;\n\
                left: 310px;\n\
                background: #D8D8D8;\n\
            }\n\
            \n\
            .operational-hours-1 {\n\
                display: flex;\n\
                margin-top: 65px;\n\
                padding-left: 155px;\n\
                padding-right: 173px;\n\
            }\n\
            \n\
            .operational-hours-what_have_we_been_up-8 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 22px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.15625px;\n\
            }\n\
            \n\
            .operational-hours-2 {\n\
                display: flex;\n\
                margin-top: 58px;\n\
                padding-left: 66px;\n\
                padding-right: 80px;\n\
            }\n\
            \n\
            .operational-hours-2-0 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                padding-top: 3px;\n\
                padding-bottom: 15px;\n\
            }\n\
            \n\
            .operational-hours-2-0-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .operational-hours-green_tick_override-7 {\n\
                width: 20px;\n\
                height: 20px;\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .operational-hours-2-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 10px;\n\
                padding-top: 1px;\n\
                padding-bottom: 5px;\n\
            }\n\
            \n\
            .operational-hours-2-1-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .operational-hours-rectangle_6 {\n\
                width: 218px;\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .operational-hours-2-2 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 2px;\n\
                padding-top: 3px;\n\
                padding-bottom: 15px;\n\
            }\n\
            \n\
            .operational-hours-2-2-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .operational-hours-green_tick_override-70 {\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .operational-hours-authenticated_facili-3 {\n\
                flex-shrink: 0;\n\
                margin-left: 9px;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.640625px;\n\
            }\n\
            \n\
            .operational-hours-3 {\n\
                display: flex;\n\
                margin-top: 23px;\n\
                padding-left: 66px;\n\
                padding-right: 98px;\n\
            }\n\
            \n\
            .operational-hours-3-0 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                padding-bottom: 2px;\n\
            }\n\
            \n\
            .operational-hours-3-0-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .operational-hours-green_tick_override-4 {\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .operational-hours-3-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 9px;\n\
                padding-top: 2px;\n\
                padding-bottom: 1px;\n\
            }\n\
            \n\
            .operational-hours-3-1-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .operational-hours-completed_patrols-1 {\n\
                width: 152px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-3-2 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 69px;\n\
                padding-top: 2px;\n\
            }\n\
            \n\
            .operational-hours-3-2-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .operational-hours-green_tick_override-8 {\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .operational-hours-3-3 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 9px;\n\
                padding-top: 2px;\n\
                padding-bottom: 1px;\n\
            }\n\
            \n\
            .operational-hours-3-3-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .operational-hours-reported_incidents-1 {\n\
                width: 152px;\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(14, 0, 63, 1);\n\
                font-size: 16px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
            }\n\
            \n\
            .operational-hours-4 {\n\
                display: flex;\n\
                margin-top: 56px;\n\
                padding-left: 102px;\n\
                padding-right: 102px;\n\
            }\n\
            \n\
            .operational-hours-rectangle_7 {\n\
                width: 391px;\n\
                flex-shrink: 0;\n\
                display: flex;\n\
                flex-direction: column;\n\
            }\n\
            \n\
            .operational-hours-5 {\n\
                display: flex;\n\
                margin-top: 73px;\n\
                padding-left: 539px;\n\
                padding-right: 47px;\n\
            }\n\
            \n\
            .operational-hours-_page_-1 {\n\
                flex-shrink: 0;\n\
                font-family: AvenirNext-Regular;\n\
                color: rgba(74, 74, 74, 1);\n\
                font-size: 14px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                font-weight: normal;\n\
                font-style: normal;\n\
                text-decoration: none;\n\
                text-align: left;\n\
                word-wrap: break-word;\n\
                padding-right: 0.875px;\n\
            }\n\
            \n\
            .operational-hours-6 {\n\
                flex-grow: 1;\n\
                flex-basis: 0px;\n\
            }\n\
            \n\
            * {\n\
                box-sizing: border-box;\n\
            }\n\
            \n\
            body {\n\
                margin: 0;\n\
            }\n\
            \n\
            button:hover {\n\
                cursor: pointer;\n\
            }\n\
            \n\
            a {\n\
                text-decoration: none;\n\
                color: inherit;\n\
            }\n\
            \n\
            .pd-onhover-parent >.pd-onhover {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > .pd-onhover {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent > .pd-onactive {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > .pd-onactive {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {\n\
                display: none;\n\
            }"
        ),
        React.createElement('div', {"className": "operational-hours-0"},
            React.createElement('div', {"className": "operational-hours-0-0"},
                React.createElement('div', {"className": "operational-hours-0-0-0"},
                    React.createElement('div', {"className": "operational-hours-0-0-0-0"},
                        React.createElement('div', {"className": "operational-hours-rectangle_1"},
                            <OperationalHoursGraph/>
                        ),
                        React.createElement('div', {"className": "operational-hours-4-5"},
                            "6"
                        ),
                        React.createElement('div', {"className": "operational-hours-6-1"},
                            "8"
                        ),
                        React.createElement('div', {"className": "operational-hours-5-1"},
                            "7"
                        ),
                        React.createElement('div', {"className": "operational-hours-sun-6"},
                            "Sun"
                        ),
                        React.createElement('div', {"className": "operational-hours-2-11"},
                            "2"
                        ),
                        React.createElement('div', {"className": "operational-hours-mon-2"},
                            "Mon"
                        ),
                        React.createElement('div', {"className": "operational-hours-fri-1"},
                            "Fri"
                        ),
                        React.createElement('div', {"className": "operational-hours-sat-1"},
                            "Sat"
                        ),
                        React.createElement('div', {"className": "operational-hours-tue-1"},
                            "Tue"
                        ),
                        React.createElement('div', {"className": "operational-hours-wed-1"},
                            "Wed"
                        ),
                        React.createElement('div', {"className": "operational-hours-thu-6"},
                            "Thu"
                        ),
                        React.createElement('div', {"className": "operational-hours-2-5"},
                            "4"
                        ),
                        React.createElement('div', {"className": "operational-hours-12"},
                            "12pm"
                        ),
                        React.createElement('div', {"className": "operational-hours-3-37"},
                            "5"
                        ),
                        React.createElement('div', {"className": "operational-hours-1-8"},
                            "3"
                        ),
                        React.createElement('div', {"className": "operational-hours-12a"},
                            "12am"
                        ),
                        React.createElement('div', {"className": "operational-hours-6p"},
                            "6pm"
                        ),
                        React.createElement('div', {"className": "operational-hours-7"},
                            "7am"
                        ),
                        React.createElement('div', {"className": "operational-hours-6a"},
                            "6am"
                        ),
                        React.createElement('div', {"className": "operational-hours-line_copy_3"}),
                        React.createElement('div', {"className": "operational-hours-line_copy-4"}),
                        React.createElement('div', {"className": "operational-hours-line_copy_6"}),
                        React.createElement('div', {"className": "operational-hours-line_copy_7"}),
                        React.createElement('div', {"className": "operational-hours-line-1"}),
                        React.createElement('div', {"className": "operational-hours-line_copy_5"})
                    )
                )
            )
        ),
        React.createElement('div', {"className": "operational-hours-1"},
            React.createElement('div', {"className": "operational-hours-what_have_we_been_up-8"},
                "What have we been up to?"
            )
        ),
        React.createElement('div', {"className": "operational-hours-2"},
            React.createElement('div', {"className": "operational-hours-2-0"},
                React.createElement('div', {"className": "operational-hours-2-0-0"},
                    React.createElement('div', {"className": "operational-hours-green_tick_override-7"},
                        <GreenTick big={false}/>
                    )
                )
            ),
            React.createElement('div', {"className": "operational-hours-2-1"},
                React.createElement('div', {"className": "operational-hours-2-1-0"},
                    React.createElement('div', {"className": "operational-hours-rectangle_6"},
                        <OperationalText clientTeamName={reportData.customerTeamName}/>
                    )
                )
            ),
            React.createElement('div', {"className": "operational-hours-2-2"},
                React.createElement('div', {"className": "operational-hours-2-2-0"},
                    React.createElement('div', {"className": "operational-hours-green_tick_override-70"},
                        <GreenTick big={false}/>
                    )
                )
            ),
            React.createElement('div', {"className": "operational-hours-authenticated_facili-3"},
                "Authenticated Facilities\nPersonnel"
            )
        ),
        React.createElement('div', {"className": "operational-hours-3"},
            React.createElement('div', {"className": "operational-hours-3-0"},
                React.createElement('div', {"className": "operational-hours-3-0-0"},
                    React.createElement('div', {"className": "operational-hours-green_tick_override-4"},
                        <GreenTick big={false}/>
                    )
                )
            ),
            React.createElement('div', {"className": "operational-hours-3-1"},
                React.createElement('div', {"className": "operational-hours-3-1-0"},
                    React.createElement('div', {"className": "operational-hours-completed_patrols-1"},
                        "Completed patrols"
                    )
                )
            ),
            React.createElement('div', {"className": "operational-hours-3-2"},
                React.createElement('div', {"className": "operational-hours-3-2-0"},
                    React.createElement('div', {"className": "operational-hours-green_tick_override-8"},
                        <GreenTick big={false}/>
                    )
                )
            ),
            React.createElement('div', {"className": "operational-hours-3-3"},
                React.createElement('div', {"className": "operational-hours-3-3-0"},
                    React.createElement('div', {"className": "operational-hours-reported_incidents-1"},
                        "Reported Incidents"
                    )
                )
            )
        ),
        React.createElement('div', {"className": "operational-hours-4"},
            React.createElement('div', {"className": "operational-hours-rectangle_7"},
                <DistanceCovered distanceCovered={reportData.distanceCovered}/>
            )
        ),
        React.createElement('div', {"className": "operational-hours-5"},
            React.createElement('div', {"className": "operational-hours-_page_-1"},
                "2"
            )
        ),
        React.createElement('div', {"className": "operational-hours-6"})
    );
};

export default function(props) {
    return render.apply({props: props});
}