// Generated by https://pagedraw.io/pages/6556
import React from 'react';
import './pilot_info.css';

function render() {
    return React.createElement('div', {"className": "pilot_info-pilot_info-2"},
        React.createElement('div', {"className": "pilot_info-0"},
            React.createElement('img', {"src": "https://ucarecdn.com/295e0f41-12b4-45b0-9787-80a6086495ef/", "className": "pilot_info-image_4"})
        )
    );
};

export default function(props) {
    return render.apply({props: props});
}