// Generated by https://pagedraw.io/pages/6556
import React from 'react';
import './videobanner.css';

function render() {
    return React.createElement('div', {"className": "videobanner-videobanner-7"},
        React.createElement('div', {"className": "videobanner-0"},
            React.createElement('div', {"className": "videobanner-gray_bar-9"},
                React.createElement('div', {"className": "videobanner-0-0-0"},
                    React.createElement('div', {"className": "videobanner-0-0-0-0"},
                        React.createElement('div', {"className": "videobanner-0-0-0-0-0"},
                            React.createElement('div', {"className": "videobanner-text_6"},
                                this.props.cameraName
                            )
                        )
                    ),
                    React.createElement('div', {"className": "videobanner-0-0-0-1"},
                        React.createElement('div', {"className": "videobanner-0-0-0-1-0"},
                            React.createElement('div', {"onClick": this.props.enlarge, "className": "videobanner-rectangle_5"})
                        )
                    )
                )
            )
        )
    );
};

export default function(props) {
    return render.apply({props: props});
}